CREATE TABLE book (
    url TEXT PRIMARY KEY NOT NULL UNIQUE,
    title TEXT,
    image TEXT,
    author TEXT,
    illustrator TEXT,
    country TEXT,
    language TEXT,
    series TEXT,
    genre TEXT,
    publisher TEXT,
    publication_date TEXT,
    media_type TEXT,
    pages TEXT,
    isbn TEXT,
    oclc TEXT,
    lc_class TEXT,
    preceded_by TEXT,
    followed_by TEXT,
    description TEXT,
    unknown TEXT []
);

CREATE TABLE author (
    url TEXT PRIMARY KEY NOT NULL UNIQUE,
    name TEXT,
    image TEXT,
    born TEXT,
    died TEXT,
    residence TEXT,
    education TEXT,
    occupation TEXT,
    period TEXT,
    genre TEXT,
    genres TEXT,
    spouse TEXT,
    children TEXT,
    pen_name TEXT,
    citizenship TEXT,
    nationality TEXT,
    years_active TEXT,
    subject TEXT,
    notable_works TEXT,
    description TEXT,
    unknown TEXT []
);